image: docker:latest
services:
  - docker:dind

stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA

test:
  stage: test
  image: node:10.8.0
  script:
    - yarn
    - yarn coverage

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  only:
    - master

heroku:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl --no-document
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://inlabs-books-api.herokuapp.com
  only:
    - master
